### PR TITLE
Version 4

### LINKED ISSUE #12: Ability to pre-load surrounding tiles when browsing
Hi, thank you for the effort in making this plugin.

I would like to get some clarification:
- Do I need to explicitly call downloadRegion to download a new Area, it does not cache automatically when a tile is downloaded when the map is moved?
- If I call downloadRegion on every map move, do tiles get downloaded again regardless if they are already downloaded and cached?

### LINKED ISSUE #23: Do not download tiles if are already saved
If we call downloadRegion it will download all tiles. Can we add extra functionality to download only not downloaded tiles?

**Describe the solution you'd like**
Get from database saved tiles, do not download this tiles

**Describe alternatives you've considered**
If we have hard coded region in app, we can check if amount of saved tiles is equal to tiles for specific region. When is equal do not download. Problem in this case is if some tiles are saved on database, because we start downloading all tiles again.

### LINKED ISSUE #26: Support Flutter 2.5
Please update to support Flutter 2.5.

### PR DESCRIPTION
**Pull request by JaffaKetchup**
See [below comment](https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/15#issuecomment-937041134) for finalised to-do list. This list will still be updated, but the aforementioned list has less items and gives a better time frame indication.
<br>
In order of priority (note that this list is subject to change, and not all of the below may actually be completed):

- [x] Support Flutter 2.5 (closes #26)
- [x] Update to a filesystem solution instead of `sqflite`
- [x] Implement automated tests
- [x] Improve `DownloadProgress` with more statistics
- [x] Add a way to recover downloads that have been incorrectly stopped
- [x] Allow better selection of caching behaviour
- [x] Remove 'network-to-file-image' dependency if necessary
- [x] Increase bulk download speeds through simultaneous download threads (merges #25)
- [x] Add option to prevent redownloading existing tiles (closes #23) 
- [x] Add option to prevent downloading tiles made of sea to save space.
- [x] Use https://github.com/fleaflet/flutter_map/pull/667 in example app
- [x] Add line region type

Unfortunately, these remaining features are taking a long time to develop, and therefore will likely be part of the next version.
- Add functionality to preload surroundings (closes #12) 
- Add widget to automatically handle source switching?
- More prebuilt solutions including a ready-to-go user-friendly cache manager screen
- Support for a potentially upcoming library (https://github.com/JaffaKetchup/flutter_osrm (currently in experimental alpha, should not be used))

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
Hi all,

I'm considering reverting all changes to do with moving to filesystem instead of `sqflite`.

 This is because it failed at its number one task of reducing grey square appearances, and it has brought more heavily breaking changes. It has, however led to some benefits: there has been a roughly 40% reduction in lines of code in the storage manager, there's now a way to get the size of one caching store instead of all of them, etc.

No idea if anyone's paying attention, but if you are, what do you think I should do? Revert or not revert?

Thanks 👍

**Comment by JaffaKetchup** [comment]
Estimated release date as of 04/08/21: +4 weeks

**Comment by JaffaKetchup** [comment]
This version is now ready for release testing, and should be released as v4.0.0 within 7 days.

**Comment by JaffaKetchup** [comment]
This should be ready for release soon!

There's a few rough edges to smooth of and a bit more automated and manual testing to write and do, but feel free to use the latest pre-release v4.0.0-dev.3: it should be mostly stable.

**Comment by JaffaKetchup** [comment]
Automated Checks appear to be broken...

**Comment by JaffaKetchup** [comment]
Automated checks are broken since Flutter 2.5.

**Comment by JaffaKetchup** [comment]
Automated checks appear to be fixed now.

Pre-release v4.0.0-dev.5 has been released on pub.dev! Enjoy. This might be one of the final pre-releases, as things seem (fingers-crossed) to be wrapping up.

**Comment by JaffaKetchup** [comment]
Remaining things to do (based on my local copy, newer than one committed here), in order of priority:
- [ ] **Fix isolate bugs**
- [ ] **... therefore fix incorrect reports of '0' tiles to download**
- [ ] Finalise line functionality
- [ ] Remove 'network-to-file-image' to allow easier (theoretically) implementation of caching behaviour selection
- [ ] Finalise documentation
- [ ] Release final pre-release as v4.0.0-dev.6 for a few days during testing to allow for external users' bug reports and suggestions
- [ ] Final release of v4.0.0 after 4 months of development

Thanks to everyone who has helped out with this update so far! Testers are appreciated: please use the latest pre-release and raise issues about bugs or suggestions!

**Comment by JaffaKetchup** [comment]
v4.0.0-dev.7 has been released! This brings major performance improvements as discussed in #29.

**Comment by codeOfJannik** [comment]
Hey @JaffaKetchup, after switching from v4.0.0-dev.6 to v4.0.0-dev.7 the reset of the TileLayerOptions with the StreamController stopped working. I had the same behaviour as described in #28 (before I was using v4-dev.6). For now I switched back to dev.6 but I'm really looking forward to the performance improvements, when the reset is working again.

**Comment by JaffaKetchup** [comment]
Hi there @codeOfJannik!
Unfortunately, I am aware of this issue, as it was reported in https://github.com/JaffaKetchup/flutter_map_tile_caching/discussions/29#discussioncomment-1607415.
As you have also reported the same issue, I will consider it an emergency bug fix: I will open a new high priority issue and any other development will wait until I can fix this or conclude it is unfixable.
Reset is likely not working due to the introduction of a custom tile provider to fix the performance issues. Hopefully I will be able to resolve the issue by resetting the image memory, but I am not 100% sure.
Thanks for your report!

**Comment by codeOfJannik** [comment]
Okay, thanks for your reply :) For me the lags in dev.6 are luckily not too bad.
I'm going to try to find time besides my work to look into the code and contribute to find a solution.

**Comment by JaffaKetchup** [comment]
@codeOfJannik Thanks, that's hugely appreciated :)

**Comment by JaffaKetchup** [comment]
Hopefully getting closer to release! See https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/31#issuecomment-1000882182.

**Comment by JaffaKetchup** [comment]
Remaining tasks:
- [ ] Finish example app
- [ ] Conduct full testing
- [ ] Release!


Sorry for keeping everyone waiting for so long! At this point, I think I'm safe to say that there will be no more breaking changes, and very few other changes apart from those mentioned above.

Thanks for your ongoing support.

**Comment by JaffaKetchup** [comment]
v4.0.0-dev.10 has been released!

**Comment by JaffaKetchup** [comment]
v4.0.0-dev.11 has been released!

**Comment by JaffaKetchup** [comment]
@bmason8 @codeOfJannik; and anyone else
If you're interested in getting the example before release later this week, please download https://drive.google.com/file/d/1Hln_HCxBpC4lH4HtWav_8-AX8Aux01z0/view?usp=sharing for the .apk, or build from the v4 branch ('/example') for another platform.
Any feedback is greatly appreciated! Just trying to iron out some bugs and test now, then it's finally release time.

**Comment by JaffaKetchup** [comment]
@bmason8 @codeOfJannik; and anyone else
Any ideas would be greatly appreciated before I release! I hope to release without too many bugs, so your testing could really help. Thanks.

**Comment by codeOfJannik** [comment]
I'll do some testing over the weekend.

Unfortunately I had to switch the way how we implement Mapbox. I can't use this library any longer in the project since my client wants me to use the mapbox_gl library to reduce the costs (active monthly users are billed with mapbox_gl instead of the amount of downloaded tiles).

I hope to have any use of your library in future projects, I really appreciate your work.

**Comment by bmason8** [comment]
I'm using v_4.0.0-dev.10 in my production code and haven't had any issues. Any performance issues I have now are all related to large geojson data sets (ie polygons and markers). Sorry if this isn't too helpful but I'm happy with where things are so I'm looking forward to an official v_4 release!

**Comment by JaffaKetchup** [comment]
@codeOfJannik that's unfortunate, but understandable. If you ever feel the need to use this again, I'll probably be here :) Many thanks.

@bmason8 That's good to hear! Hopefully it should come tomorrow, or Sunday at the latest.

**Comment by JaffaKetchup** [comment]
v4.0.0 final has been released! Thanks for your support, and I'll be happy to do bug fixes should I have missed anything.

Note that the LICENSE has changed, and this project now runs under the GNU AGPLv3. Please donate if you can - kofi doesn't take a fee!

**Pull request merged**
