### PR TITLE
v7.2.0: Major bug fixes and improvements

### LINKED ISSUE #59: [BUG] Unsupported operation: Watching is not supported on the current platform
**Describe The Bug**
App crashes in first run on iOS. using the official example with all dependencies installed.

**Expected Behaviour**
App should run and (i do not know what is next, i just wanted to try out the package)

**Screenshots & Recordings**
```dart
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            5.4s
Debug service listening on ws://127.0.0.1:51342/bKfPVmvulqU=/ws
Syncing files to device iPhone 13...
../lib/src/internal/image_provider.dart:75:23: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
      PaintingBinding.instance?.imageCache?.evict(this);
                      ^
../lib/src/internal/image_provider.dart:88:27: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
          PaintingBinding.instance?.imageCache?.evict(this);
                          ^
../lib/src/internal/image_provider.dart:98:27: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
          PaintingBinding.instance?.imageCache?.evict(this);
                          ^
../lib/src/internal/image_provider.dart:140:23: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
      PaintingBinding.instance?.imageCache?.evict(this);
                      ^
lib/pages/store_manager/store_manager.dart:124:55: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
                                      PaintingBinding.instance?.imageCache
                                                      ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/feature_discovery-0.14.1/lib/src/widgets/layout.dart:92:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/feature_discovery-0.14.1/lib/src/widgets/layout.dart:112:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/backdrop-0.7.2/lib/src/scaffold.dart:713:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((_) => _notify());
                     ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/backdrop-0.7.2/lib/src/scaffold.dart:716:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) => _notify());
                         ^

======== Exception caught by widgets library =======================================================
The following UnsupportedError was thrown building Consumer<GeneralProvider>(dirty, dependencies: [_InheritedProviderScope<GeneralProvider?>]):
Unsupported operation: Watching is not supported on the current platform

The relevant error-causing widget was: 
  Consumer<GeneralProvider> Consumer:file:///Users/azat/Developer/Flutter/flutter_map_tile_caching/example/lib/pages/home/components/panel/panel.dart:26:16
When the exception was thrown, this was the stack: 
#0      MapCachingManager.watchStoreChanges (package:flutter_map_tile_caching/src/storage_managers/storage_manager.dart:201:7)
#1      Panel.build.<anonymous closure> (package:fmtc_example/pages/home/components/panel/panel.dart:32:27)
#2      Consumer.buildWithChild (package:provider/src/consumer.dart:179:19)
#3      SingleChildStatelessWidget.build (package:nested/nested.dart:259:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4876:49)
#5      SingleChildStatelessElement.build (package:nested/nested.dart:279:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#10     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (51 frames)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#62     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#63     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (9 frames)
#72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#77     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#78     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#79     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#80     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#81     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#82     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#86     _invoke (dart:ui/hooks.dart:151:10)
#87     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#88     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

**Additional Information**
Add any other context about the problem here, or remove this section.

I think we need to implement some platform-aware methods for platform specific cases.

---

**Doctors Report**

```shell
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**To Reproduce**
Steps to reproduce the behaviour:

Just build the project and launch it on iOS

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [ ] Non-Fatal
- [x] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

### LINKED ISSUE #103: [BUG] Repeating download raises exception
### What is the bug?

I repeated (on button press) cache download and got the exception:
`/flutter (23312): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_progressManagement@1508177007' has not been initialized.
E/flutter (23312): #0      DownloadManagement._progressManagement (package:flutter_map_tile_caching/src/store/download.dart)
download.dart:1
E/flutter (23312): #1      DownloadManagement.cancel
download.dart:128
E/flutter (23312): <asynchronous suspension>
E/flutter (23312):
I/flutter (23312): Total markers:0
I/flutter (23312): Total paths:1`

### What is the expected behaviour?

No exception.

### How can we reproduce this issue?

My code:
```
       if (globals.connected) {
            await DialogsFactory()
                .confirmationDialog(context, "Offline maps",
                    "Do you want to download maps and data for selected view for offline use ? The operation might take some time.")
                .then((download) async {
              if (download!) {
                int successfulTiles = 0;
                int tiles = 0;
                // define region
                TileLayer streetMapOptions = TileLayer(
                  minZoom: globals.minOfflineZoom,
                  maxZoom: globals.maxOfflineZoom,
                  urlTemplate: "https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}",
                  additionalOptions: {
                    'accessToken':
                        'XXXX',
                    'id': _mapStyle,
                  },
                );

                TileLayer satMapOptions = TileLayer(
                  minZoom: globals.minOfflineZoom,
                  maxZoom: globals.maxOfflineZoom,
                  urlTemplate:
                      "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg",
                );

                // define region
                final region = RectangleRegion(_bounds);
                final downloadableStreet = region.toDownloadable(
                    globals.minOfflineZoom.toInt(), globals.maxOfflineZoom.toInt(), streetMapOptions,
                    parallelThreads: 20, preventRedownload: true, seaTileRemoval: true);
                final downloadableSat = region.toDownloadable(
                    globals.minOfflineZoom.toInt(), globals.maxOfflineZoom.toInt(), satMapOptions,
                    parallelThreads: 20, preventRedownload: true, seaTileRemoval: true);
                // download manager
                _managerStreet = FlutterMapTileCaching.instance(globals.streetMapCacheStoreName).download;
                _managerSat = FlutterMapTileCaching.instance(globals.satMapCacheStoreName).download;
                tiles = await _managerStreet.check(downloadableStreet) + await _managerSat.check(downloadableSat);
                if (kDebugMode) {
                  print("Tiles to download $tiles\n");
                }
                setState(() {
                  _isDownloading = true;
                  _progressValue = 0;
                  _dowloadMessage = "Dowloading map tiles 0/$tiles";
                });
                final broadcastStream = FMTC
                    .instance(globals.satMapCacheStoreName)
                    .download
                    .startForeground(region: downloadableSat, bufferMode: DownloadBufferMode.tiles)
                    .asBroadcastStream();

                await broadcastStream.listen((event) {
                  Future.delayed(Duration(milliseconds: 50)).then((onValue) {
                    setState(() {
                      _progressValue = successfulTiles / tiles;
                      successfulTiles = event.successfulTiles;
                      _progressKey = Object();
                      _dowloadMessage = "Dowloading map tiles  $successfulTiles/$tiles";
                      // check if not canceled
                      if (!_isDownloading) {
                        _managerSat.cancel();
                        return;
                      }
                    });
                  });
                }, onDone: () {
                  if (!_isDownloading) {
                    return;
                  }
                  setState(() {
                    _progressValue = (successfulTiles) / tiles;
                    ;
                    _dowloadMessage = "Dowloading map tiles $successfulTiles/$tiles";
                  });

                  final broadcastStream = FMTC
                      .instance(globals.streetMapCacheStoreName)
                      .download
                      .startForeground(region: downloadableStreet, bufferMode: DownloadBufferMode.tiles)
                      .asBroadcastStream();
                  broadcastStream.listen((event) {
                    Future.delayed(Duration(milliseconds: 100)).then((onValue) {
                      setState(() {
                        _progressValue = (successfulTiles + event.successfulTiles) / tiles;
                        _progressKey = Object();
                        _dowloadMessage = "Dowloading map tiles  ${(successfulTiles + event.successfulTiles)}/$tiles";
                        if (!_isDownloading) {
                          _managerStreet.cancel();
                          return;
                        }
                      });
                    });
                  }).onDone(() async {
                    await cacheFieldsInView(_bounds).then((value) {
                      setState(() {
                        _isDownloading = false;
                      });
                    });
                  });
                });
              } // if download
            });
          } else {
            await DialogsFactory().infoDialog(context, "No connection",
                "Looks like there is no Internet connection necessary to download maps and data.");
          }
```

### Do you have a potential solution?

Ignore exception.

### Can you provide any other information?

_No response_

### Platforms Affected

Android

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

### PR DESCRIPTION
**Pull request by JaffaKetchup**
- Stability improvements
  - Starting multiple downloads no longer causes LateInitializationErrors (https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/103)
  - Migrator storage and memory usage no longer spikes as significantly as previously, thanks to transaction batching (part of https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/105)
  - Opening and processing of stores on initialisation is more robust and less error-prone to filename variations (https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/106)
  - Root statistic watching now works on all platforms (re-occurence of https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/59, also note https://github.com/dart-lang/sdk/issues/51549)
- Multiple minor bug fixes and documentation improvements
- Added maxStoreLength config to example app

_Closes #106, closes #103, closes #59._

With thanks to @sikandernoori and @Mmisiek.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
@sikandernoori Can you test this branch within your application when you get a moment please, to ensure that I have actually resolved your issues?

**Comment by sikandernoori** [comment]
> @sikandernoori Can you test this branch within your application when you get a moment please, to ensure that I have actually resolved your issues?

I test the plugin with example application, will update you if all functionality working okay.
Also if would be convenient for me if we add IOS support/folder in example app.

**Comment by sikandernoori** [comment]
The one I reported are Good but there are other Bugs I faced on this branch.
It happens when I try to delete store.

Error screenshot and video attached.

Screenshot 2023-03-02 at 1 48 35 PM



https://user-images.githubusercontent.com/16399272/222421432-7d569010-8e3f-4c75-95b8-d01b7e14f4da.mp4

**Comment by sikandernoori** [comment]
> The one I reported are Good but there are other Bugs I faced on this branch. It happens when I try to delete store.

It does not make to the console though, so maybe nothing needs to be done here.

**Comment by JaffaKetchup** [comment]
Not sure about that one, that's a little more unusual. I've possibly got something wrong there, I'll investigate.

**Pull request merged**
