### PR TITLE
Version 5

### PR DESCRIPTION
**Pull request by JaffaKetchup**
Currently completed tasks:

- [x] Remove artefacts and deprecated APIs from v3 to v4 migration
- [x] Use a simpler, shorter API to use most functionality (see below)
- [x] Separate tile storage from other storage, such as metadata and stat caching - allowing for...
    - [x] Cache expensive statistics in the filesystem, thus greatly increasing performance
    - [x] Add of more complex statistics, such as suggested in a comment (https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/44#issuecomment-1160825205)
- [x] Allow more than one download recovery per store
- [x] Add metadata - simple key/value pair filesystem based - storage
- [x] Add filesystem migration detection and methods for v4 stores

Other planned tasks such as:

- Archiving of stores and exporting to external storage and/or sharing
- Methods to conveniently use 'flutter_osrm' (currently in unstable alpha)

... will now be implemented at a later stage, potentially as part of v5.1.0

---

There will be major breaking changes as part of this. Apologies for any inconvenience caused by this.

- v4 stores will be incompatible with v5 (this may be fixed by a built-in detector and fixer)
- v4 syntax will be mostly incompatible with v5

---

There is currently no due date. In fact, at present, there is no guarantee that this will be implemented, due to external limitations. I have not pre-tested anything, so all is subject to change.

### CODE REVIEW

**Comment by tonyshkurenko** [comment]
Hi, I'm trying to come up with how to use v5 (I'm starting a new project, I just don't want to use v4, since v5 is coming soon), I wanted to ask a couple of questions:
1) When do you expect to release?
2) Is it possible to have some debug logs (or as part of stats) cache hits and misses, not only storage amount

Thanks!

**Comment by JaffaKetchup** [comment]
Hi there @tonyshkurenko, it's great to hear about your interest!

Good plan using v5, it's nothing like v4, and (I fear) will be a hassle to migrate after all.

In terms of an estimated release date, I'm not 100% sure. 
Right now I'm writing docs (you should check out the new documentation website from the v5 branch README), and writing the new example app. After this, I need to do full testing as I haven't had a real opportunity yet. After that, it should be done.
I'm thinking about leaving the compression stuff for v5.1 (no major API changes), to speed this up.

If you are concerned about stability, then I'd say I'm fairly sure not much is going to change now, so it's probably stable in that way. Testing/functionality wise, I have little idea yet, but maybe you could shine a light onto that if you are already using it?

That is quite a good idea for cache hits/misses, and easy enough to implement. I'll try to get that done :)

If there is any other feedback or questions, I'd love to hear it! Out of interest, what are you going to be using this library for?

Thanks!

**Comment by tonyshkurenko** [comment]
I came back to the old project. I've created issue in flutter_map once: https://github.com/fleaflet/flutter_map/issues/941

Regarding testing:

I checked your example, where you use two separate caches: https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/v5/example/lib/main.dart

I mean `Store Alpha` and `Store Beta`. I assume they should save tiles separately and use them separately too. But in my case, where I have two tile layers it seems that cache only works for one, despite have two folders. Here's parts of my code:

```

final tileCache = FMTC.instance['cache'];
final tileCacheOverlay = FMTC.instance['overlay'];

FlutterMap(
            mapController: mapController,
            options: MapOptions(
              center: LatLng(37.330222, -122.023472),
              zoom: 13.0,
            ),
            layers: [
              TileLayerOptions(
                urlTemplate:
                    "https://api.mapbox.com/styles/v1/tonyshkurenko/somehash123/tiles/256/{z}/{x}/{y}@2x?access_token={accessToken}",
                additionalOptions: {
                  'accessToken':
                      'token'
                },
                tileProvider: tileCache.getTileProvider(),
                tileBuilder: (ctx, tileWidget, tile) {
                  return Container(
                    decoration: BoxDecoration(
                      border: Border.all(),
                    ),
                    child: Stack(
                      fit: StackFit.passthrough,
                      children: [
                        tileWidget,
                        Center(
                          child: Text(
                            "Inner: ${tile.coords}",
                            style: Theme.of(context).textTheme.headline5,
                          ),
                        ),
                      ],
                    ),
                  );
                }
              ),
              TileLayerOptions(
                urlTemplate:
                    "https://api.mapbox.com/styles/v1/tonyshkurenko/someotherhash2/tiles/256/{z}/{x}/{y}@2x?access_token={accessToken}",
                additionalOptions: {
                  'accessToken':
                      'token',
                },
                tileProvider: tileCacheOverlay.getTileProvider(),
                backgroundColor: Colors.transparent,
                  tileBuilder: (ctx, tileWidget, tile) {
                    return Container(
                      decoration: BoxDecoration(
                        border: Border.all(),
                      ),
                      child: Stack(
                        fit: StackFit.passthrough,
                        children: [
                          tileWidget,
                          Center(
                            child: Text(
                              "Outer: ${tile.coords}",
                              style: Theme.of(context).textTheme.headline5,
                            ),
                          ),
                        ],
                      ),
                    );
                  }
              ),
            ],
          ),
```


Real code is a bit more complex, but even this one catches the issue. So I have 2 separate styles in Mapbox so I expect to have overlay in a different style, but it has the same style as the inner layer. I've added labels, to see if layers are working correctly and they do.

My conclusions and assumptions:
1) I've checked file structure and I see both folders (but only one is filled)
2) I assume because the only difference is in style name (hash), but coords+zoom are the same, perhaps it reuses some download cache (or something like that)

P.S. I do something similar to https://fogofworld.app where you uncover basic map with more detailed

**Comment by tonyshkurenko** [comment]
I tried to follow some code to check if there are any singletons or similar things (anything which can be shared between two instances), and I've found those things:

(I'm no expert in flutter deeps, so it may be irrelevant)

https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/v5/lib/src/internal/image_provider.dart#L163 and `FMTCImageProvider` has equals based on coords: https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/v5/lib/src/internal/image_provider.dart#L176-L179


Overall as a quickfix I believe if equals method has comparison of store name too, it may be fixed

**Comment by JaffaKetchup** [comment]
Hi there, thanks for the info.

I can confirm that your example looks like it should work, so if that bugs, then it's an issue in here: as you said.

Not sure what you mean by your point 2, but point 1 is interesting - definitely both should be being filled. I'll have to probably debug the custom tile provider to get to the bottom of this one.
Note that the fact two folders exist is relatively uninteresting, as the square brackets auto create the store's folder (not recommended, use parenthesis in future if possible). The issue is only one being filled.

In terms of the equality solution, this is probably irrelevant. That just managed checking whether an `FMTCImageProvider` is the same as another, and is not used internally. I'll try it anyway, just to be sure.

I'll try to dig to the bottom of this sooner rather than later. At the moment I'm busy with exams so can't do much coding, but they are mostly done by next weekend.

Thanks 👍.

**Comment by tonyshkurenko** [comment]
Good luck with your exams!

**Comment by pablojimpas** [comment]
Out of curiosity, what's the rationale behind having a custom set of linter rules? Wouldn't it be more practical and easier to maintain to just have the same [lints as flutter_map itself](https://github.com/fleaflet/flutter_map/blob/bee620c979fd990f3f22cc23f17aafdc949b530d/analysis_options.yaml)? which are reasonably sensible.

**Comment by pablojimpas** [comment]
> I see what you mean about being easier to maintain. However, I found the default lints too lax and there were some rules I wanted that weren't in other lints. Hopefully this will enforce a more consistent style, as there were quite a few differences between files in v4, as time moved along.

Okey, I understand your concern of enforcing stricter rules, after reading [this comparison](https://rydmike.com/blog_flutter_linting.html) a while ago I usually just go with `very_good_analysis` for my own apps/packages. Having said that, as long as you don't bother dealing with managing a custom set rules everything it's ok, the rules look good to me, maybe we can gradually enforce stricter rules in the future in `flutter_map` itself.

**Comment by FireAndIceFrog** [comment]
Hi there! Is there any plan to add desktop support for this plugin?

**Comment by FireAndIceFrog** [comment]
This is fantastic work, it must have taken you a very long time to do it, great job!

**Comment by JaffaKetchup** [comment]
@FireAndIceFrog I haven't tested desktop support, but there is no reason it shouldn't work!

**Comment by JaffaKetchup** [comment]
@FireAndIceFrog Would like to know how you got on with desktop support, if you've tried it yet!

**Comment by FireAndIceFrog** [comment]
> @FireAndIceFrog Would like to know how you got on with desktop support, if you've tried it yet!

Ive only tried it on windows, works like a charm :)

**Comment by JaffaKetchup** [comment]
Great to hear :). Out of interest, do you know where the `RootDirectory.normalCache` actually is on Windows? It's different on every platform.

**Comment by FireAndIceFrog** [comment]
> Great to hear @FireAndIceFrog :). Out of interest, do you know where the `RootDirectory.normalCache` actually is on Windows? It's different on every platform.

Directory is current_user/documents directory

**Comment by tonyshkurenko** [comment]
Is there any way to test the latest build without releasing dev-3? I'd like to use it already :)

**Comment by JaffaKetchup** [comment]
@tonyshkurenko
Absolutely. You should be able to use dependency_overrides: see https://fmtc.jaffaketchup.dev/get-started/installation#from-github.com. The branch name is 'v5'. Note that master is not necessarily stable!

**Comment by JaffaKetchup** [comment]
@tonyshkurenko Thanks for alerting me to that, I've corrected it. Note that I've just broken background downloading, so it won't work. You may also need to perform additional undocumented installation instructions: https://pub.dev/packages/flutter_foreground_task#getting-started.

**Comment by JaffaKetchup** [comment]
If anyone has experience with implementing reliable downloading in the background, I'd love to know about it! I'm struggling with replacing the current bulk downloading implementation (it wasn't reliable enough for my liking), and trying to use '[flutter_foreground_task](https://pub.dev/packages/flutter_foreground_task)' to do this. Unfortunately, it seems to have lots of limitations.

**Comment by tonyshkurenko** [comment]
Hi, do you have a complete list of features planned for v5? I haven't seen downloading refactor in the list above, that's why I'm asking. Sadly I don't have enough experience with it to help (and I don't use this feature). You're doing great job

**Comment by JaffaKetchup** [comment]
Hi @tonyshkurenko,

You are right, I wasn't planning to refactor the download system. I've been working on it, but I can't get it better than it is, so I might rollback my changes (harder than it sounds because I made some other useful changes inbetween it all).

Once I've rolled back, if that's what I do, then it's just the features in the [body of this PR](https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/44#issue-1151997175) that are planned.

I've now got about 4-6 weeks of freetime - now on my summer break - so this version should easily be released by the end of this time, if not sooner.

Thanks for your interest, and it means a lot to me that it's working well for you :). Not sure if I've asked you before, but if you can donate even a small amount, that would be great! No worries if you can't :)

**Comment by JaffaKetchup** [comment]
@tonyshkurenko @pablojimpas @FireAndIceFrog @sn4k3ch4rm3r and other interested people

v5.0.0-dev.3 has been released to pub.dev. Note that there have been some major changes to the background downloading. Please let me know how you get on!

**Comment by JaffaKetchup** [comment]
Anyone interested, there are now prebuilt example applications available for you to test and experiment with at https://github.com/JaffaKetchup/flutter_map_tile_caching/tree/v5/prebuiltExampleApplications. These are automatically kept up to date with every commit.

Estimated time now until release is by the end of 2 weeks time max, more likely about 1 week. Looking forward to it!

**Comment by JaffaKetchup** [comment]
Now's the time to report a bug or a quick feature you want, anyone here. Everything is pretty much ready!

@tonyshkurenko Thanks for your donation, you're now on the [Sponsors list](https://fmtc.jaffaketchup.dev/sponsors)!

If anyone else can donate, I now have a verified GitHub Sponsors account: https://github.com/sponsors/JaffaKetchup. Please donate any amount you can spare, one-time or monthly. This update has taken a huge amount of time and effort, so any amount means a lot to me!

**Comment by JaffaKetchup** [comment]
Thanks to everyone who has stayed around and/or supported me. Feels good to finally have this ready, and I'm happy to answer any questions you may have.

In terms of migration, I haven't provided any specific instructions, so you'll need to figure it out from the new documentation or ask me.
It is important to note this page: https://fmtc.jaffaketchup.dev/usage/roots-and-stores/migrator. You should definitely add this to your app before publishing a new version of it.

It's taken [this long](https://www.timeanddate.com/date/durationresult.html?d1=26&m1=02&y1=2022&d2=3&m2=8&y2=2022&ti=on) to get this version released, so please, if you can spare any change, donate to me via the button at the top of this page.

Any feedback is appreciated, and I'd love to know your reasons for using this library!

**Comment by tonyshkurenko** [comment]
Gratz!

**Pull request merged**
