### PR TITLE
Version 3.0.0

### PR DESCRIPTION
**Pull request by JaffaKetchup**
Repairs and adds features intended to make the plugin easier and more useful to use for end users, and improve performance and integration for developers.

- [x] Add more options for region selection including Line, Circle & Polygon
- [ ] Add a special `PolygonLayer` to allow tap/drag selection of a region to be downloaded
- [ ] Add multiple caches to support multiple tile servers
- [x] Allow background downloading in a separate Isolate (help wanted, see pinned issue)
- [x] Make code more transparent through use of comments
- [x] Improve HTTP request performance

Any other features anyone would like to see? Feel free to make your own PR to the v3-testing branch, or raise an issue with the v3 Release milestone!

### CODE REVIEW

**Comment by bmason8** [comment]
I appreciate the effort on this and have a question regarding points 1 and 2...Do either of those mean it will be possible to pass in multiple `LatLngBounds` into the `loadTiles()` method? I have the need to cache multiple areas that don't overlap and can be far apart (so creating one huge cached area isn't possible/ideal).

**Comment by JaffaKetchup** [comment]
Hi @bmason8,
I guess I could add this, but couldn't you just call the function for every region/area?

**Comment by bmason8** [comment]
> Hi @bmason8,
> I guess I could add this, but couldn't you just call the function for every region/area?

@JaffaKetchup Yeah if that's a viable option then that's great!  Sorry, I only started using this package today so I'm not too familiar with it yet and didn't realized it could be used like that. Thanks for the reply!

**Comment by JaffaKetchup** [comment]
@bmason8 Not to worry! Is there anything I could add to the documentation to make this clearer?

**Comment by bmason8** [comment]
@JaffaKetchup No I think it's good! Now that I've been using it for a day I understand what's going on. I just made some incorrect assumptions right off the start which go me a little confused. Thanks again for this package! It's making offline mapping sooo much easier!

**Comment by JaffaKetchup** [comment]
@bmason8 Great to hear it helps! If you don't mind, a star (GitHub) and a like (pub.dev) would be greatly appreciated!

**Comment by JaffaKetchup** [comment]
Repairs and adds features intended to make the plugin easier and more useful to use for end users, and improve performance and integration for developers.

- [ ] Add more options for region selection including Line, Circle & Polygon
- [ ] Add a special `PolygonLayer` to allow tap/drag selection of a region to be downloaded
- [ ] Add multiple caches to support multiple tile servers
- [ ] Allow background downloading in a separate Isolate (help wanted, see pinned issue)
- [x] Make code more transparent through use of comments
- [x] Improve HTTP request performance

Any other features anyone would like to see? Feel free to make your own PR to the v3-testing branch, or raise an issue with the v3 Release milestone!

**Comment by JaffaKetchup** [comment]
Updated aims, see main post.

**Comment by JaffaKetchup** [comment]
Release planned within 72 hours.

**Comment by JaffaKetchup** [comment]
Changing base branch...

**Comment by JaffaKetchup** [comment]
See #4 for more info.

**Pull request closed without merging**
