### PR TITLE
Migration to null-safety

### LINKED ISSUE #1: Null-safe support
Thanks for the great work with this plugin. Is a null-safe version in the near future plans or should I just go ahead an convert it? I assume we are waiting for a official null safe flutter_map package first.

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This should be fully working. As soon as the branch gets released as official release, I will update this PR appropriately and you can merge this PR right after that.

Alternatively, you can merge this right now and I will create another PR at a later point or you change it yourself then :)

Closes #1

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
Hi, thanks for the PR @ThexXTURBOXx, it's greatly appreciated 👍.

I don't mind if you want to change this when `flutter_map` nullsafety is released, so I'll keep this PR open until then. Also, many thanks for spotting the `pubspec.lock` file I accidentally left in! Have you fully re-tested this fork, or are you assuming it'll work, because I was intending to fully test it again, but I'm not sure if that's necessary?

Before publishing this updated package to pub.dev, however, I need to make some changes, including documentation and variable defaults; I'll do that after this fork has been merged, to avoid conflicts. After that I'll publish to pub.dev.

Whilst you're waiting, it would help to give a star on GitHub and a like on [pub.dev](https://pub.dev/packages/flutter_map_tile_caching)!

Thanks,
Luka S

**Comment by ThexXTURBOXx** [comment]
No problem :)

Okay, perfect! Then I will change it as soon as null-safety is released. If I forget to do it, just mention me once here and remind me and it shouldn't take me too long (assuming I am awake here in Germany).

I haven't _fully_ retested it, but the basic functionality seems to work for me at least. It would be very nice if someone else could also test this. So, to anyone reading this: You can test my branch by using a `dependency_override` in your `pubspec.yaml` like this:
```yaml
dependency_overrides:
  flutter_map_tile_caching:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_map_tile_caching.git
      ref: main
```

I am looking forward to the release! :)

**Comment by JaffaKetchup** [comment]
Hi @ThexXTURBOXx, 
A small change of plan, I will release 2.0.0 as the next major version, containing this fork, planned organisational changes, planned default changes and a fix for a new issue (https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/3). This is to prevent two major versions being released so close to each other.
Therefore, when updating this fork finally for the null-safe release of `flutter_map`, could you also address my requested changes on your latest commit.
Thanks again!

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
- Change `changelog.md` newest release version to **1.1.0**
- Change `readme.md` installation instructions back to version **1.0.1** (specifically this version to avoid people needing to update twice in a short amount of time, see my comment on the main conversation feed)
- Change `pubspec.yaml` version to **1.1.0**

**Review by JaffaKetchup — APPROVED** [review]

**Comment by JaffaKetchup** [comment]
Ok, so all that needs to be done in here now is check over the sound null-safety when `flutter_map` null-safety is finally released. Then, ASAP, I will make more breaking changes to release version 2.0.0.

Is it still ok for you to make the changes in here when `flutter_map` null-safety is released?

**Comment by ThexXTURBOXx** [comment]
Yes, of course! Thanks for already changing the version to 1.1.0 and so on. I will check this PR again when the null-safe `flutter_map` is released.

**Comment by JaffaKetchup** [comment]
Hi, noticed you fixed a few more things!
Does that mean it's ready to go now? I've seen that you're using dependency overrides to get the null-safe version of `flutter_map`, so surely it is all now soundly null safe?
If it's ready to go now, I can merge it now, and just change the `flutter_map` dependency at some point in the future?
I can't say thank you enough 👍.

**Comment by ThexXTURBOXx** [comment]
Hi, the last commit was just a small cleanup, not much :)

I think, it should be ready to go, but surely some more testing is needed.

Yes, you can just remove the `dependency_overrides` section as soon as `flutter_map` is released. Then you need to update `flutter_map`'s version and you can most likely immediately release your plugin :)

No problem! ^^

**Comment by JaffaKetchup** [comment]
Ok, sure. I will carry out some testing before merging this, almost forgot about that!
Then, this will be ready, and I'll merge it (hopefully) as planned.

**Comment by JaffaKetchup** [comment]
I'm pretty sure it's good to go! Many thanks once again :).

**Comment by JaffaKetchup** [comment]
Turns out, I can't publish this with a git dependency or an override, so for the time being, 2.0.0 is only available on GitHub. Oh well!

**Comment by ThexXTURBOXx** [comment]
Yes, I know :/

The problem is both, actually. You can't have neither a git dependency nor an override :/

**Pull request merged**
